# buildbot-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: buildbot-master
  namespace: buildbot
  labels:
    app: buildbot
    tier: master
spec:
  ports:
    - port: 8080
      name: frontend
    - port: 9989
      name: worker
  selector:
    app: buildbot
    tier: master
  type: NodePort
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildbot-pv-claim
  labels:
    app: buildbot
    tier: master
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildbot-master
  labels:
    app: buildbot-master
    tier: master
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: buildbot-master
        tier: master
    spec:
      containers:
      - name: buildbot-master
        image: buildbot/buildbot-master:v0.9.9.post2
        env:
        - name: BUILDBOT_CONFIG_DIR
          value: config
        - name: BUILDBOT_CONFIG_URL
          value: 'https://raw.githubusercontent.com/XiniX00/buildbot-on-kubernetes/master/simple/master.cfg'
        - name: BUILDBOT_WORKER_PORT
          value: '9989'
        - name: BUILDBOT_WEB_URL
          value: 'http://localhost:8080/'
        - name: BUILDBOT_WEB_PORT
          value: '8080'
        ports:
        - containerPort: 8080
          name: frontend
        - containerPort: 9989
          name: worker
        volumeMounts:
        - name: buildbot-persistent-storage
          mountPath: /var/lib/buildbot/builds
      volumes:
      - name: buildbot-master-persistent-storage
        persistentVolumeClaim:
          claimName: buildbot-master-pv-claim
