# local-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    app: buildbot
    tier: master
  name: buildbot-master-pv
  namespace: buildbot
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: buildbot-master-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  labels: 
    app: buildbot
    tier: worker
  name: buildbot-worker-pv
  namespace: buildbot
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: buildbot-worker-disk
    fsType: ext4