# worker-deployment.yaml
apiVersion: v1
kind: Service
metadata:
  name: buildbot-worker
  namespace: buildbot
  labels:
    app: buildbot
    tier: worker
spec:
  ports:
  - port: 9989
    name: worker
  selector:
    app: buildbot
    tier: worker
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: buildbot-worker-pv-claim
  labels:
    app: buildbot
    tier: worker
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: buildbot-worker
  labels:
    app: buildbot
    tier: worker
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: buildbot
        tier: worker
    spec:
      containers:
      - image: "buildbot/buildbot-worker:v0.9.9.post2"
        name: worker
        env:
        - name: BUILDMASTER
          value: master
        - name: BUILDMASTER_PORT
          value: '9989'
        - name: WORKERNAME
          value: example-worker
        - name: WORKERPASS
          value: pass
        - name: WORKER_ENVIRONMENT_BLACKLIST
          value: 'DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST'
        ports:
        - containerPort: 9989
          name: worker
        volumeMounts:
        - name: buildbot-worker-persistent-storage
          mountPath: /buildbot/builds
      volumes:
      - name: buildbot-worker-persistent-storage
        persistentVolumeClaim:
          claimName: buildbot-worker-pv-claim
